### ISSUE TITLE
Bug: "Cannot save file into a non-existent directory: 'ghrs-data'"

### ISSUE THREAD

**Issue by olets** [jgehrcke/github-repo-stats#86]
I'm getting the following error:

```shell
# ---snip---
240111-23:31:30.123 INFO:MainThread: write fork time series to forks-raw.csv.tmp, then rename to forks-raw.csv
240111-23:31:30.124 INFO:MainThread: current stargazer count as reported by repo properties: 1
240111-23:31:30.124 INFO:MainThread: does not exist yet: ghrs-data/stargazer-snapshots.csv
240111-23:31:30.124 INFO:MainThread: write cumulative/snapshot-based stargazer time series to ghrs-data/stargazer-snapshots.csv.tmp, then rename to ghrs-data/stargazer-snapshots.csv
Traceback (most recent call last):
  File "//fetch.py", line 596, in <module>
    main()
  File "//fetch.py", line 114, in main
    fetch_and_write_stargazer_ts(repo, args)
  File "//fetch.py", line 199, in fetch_and_write_stargazer_ts
    updated_sdf.to_csv(tmppath, index_label="time_iso[86](https://github.com/olets/stats/actions/runs/7495644051/job/20406129701#step:3:87)01")
  File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 3[90](https://github.com/olets/stats/actions/runs/7495644051/job/20406129701#step:3:91)2, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/usr/local/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/usr/local/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/usr/local/lib/python3.10/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/usr/local/lib/python3.10/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'ghrs-data'
+ FETCH_ECODE=1
+ set +x
error: fetch.py returned with code 1 -- exit.
```

One possible complicating factor is the repo is only two days old. If I remember correctly we've seen before that there may be weirdnesses with young repos, where Github isn't storing data yet.

I haven't looked into the source, but the error reads to me like this isn't a GitHub problem.

Can email you a short-lifespan token if you want to experiment.

**Comment by olets** [comment]
Workflow succeeded after I manually created, committed, and pushed `path/to/ghrs-data/.gitkeep`.

This is using `jgehrcke/github-repo-stats@HEAD` (so that I can have #75 without waiting on a release)

**Comment by olets** [comment]
Ha came to write up this same issue, and this same solution, with a different two day old repo. Leaving a comment in hopes that it helps me remember next time!
